### PR TITLE
Add wemake-python-styleguide

### PR DESCRIPTION
**Pull request by sobolevn**
`wemake-python-styleguide` is the strictest linter in the python's ecosystem.
It also feature around 1000 automated rules of how to write idiomatic python code.
Including: complexity, naming standards, best practices, and enforcing pythonic ways of doing things.

It also has nice docs about all the rules and features inside: https://wemake-python-stylegui.de/en/latest/
Repo: https://github.com/wemake-services/wemake-python-styleguide

### CODE REVIEW

**Comment by sobolevn** [comment]
@palash25 friendly ping 🙂

**Comment by palash25** [comment]
Hi @sobolevn sorry I missed this, I was looking at it and this looks more like a linter rather than a piece of literature on best practices in python

Maybe a link to a page with a list of formatting rules available or enforced by this linter would be a better contribution to this repo

**Comment by sobolevn** [comment]
Like this one? https://wemake-python-stylegui.de/en/latest/pages/usage/violations/index.html

**Comment by palash25** [comment]
Quite close I guess, can you please update the link and a some sort of a note in a bracket something like this  

```
wemake-python-styleguide (contains a list of stylistic rules / guidelines for Python code)
```

**Comment by sobolevn** [comment]
@palash25 done! Thanks a lot for your help 👍

**Comment by palash25** [comment]
thank you @sobolevn

**Pull request merged**
